name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        if: success()
        uses: felicitadaniel/TIC-TAC-TOE@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist//tic-tac-toe-game
          enable_jekyll: true
