name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/tic-tac-toe-game/browser --no-silent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
